[package]
name = "cairo_read_only_call"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.12.2"


[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.12.2"
alexandria_data_structures = "0.6.1"

[dev-dependencies]
snforge_std = "0.50.0"
assert_macros = "2.12.0"

[scripts]
test = "snforge test"

[lib]
